cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove,
         name='cart_remove'),]

feedback/urls.py
from django.urls import path
from . import views

app_name = 'feedback'
urlpatterns = [
    path('create/', views.feedback_create, name='feedback_create'),
    ]

myshop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('cart',include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('feedback/', include("feedback.urls")),
    path('login/', include('django.contrib.auth.urls')),
    path('', include('shop.urls', namespace='home')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views
app_name = 'shop'
urlpatterns = [path('', views.product_list, name='product_list'),
               path('<slug:category_slug>/', views.product_list,
                    name='product_list_by_category'),
               path('<int:id>/<slug:slug>/', views.product_detail,
                    name='product_detail'),
                path('shop/', views.product_list),
                path('shop/', views.product_detail),
]

shop/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=200,
    db_index=True)
    slug = models.SlugField(max_length=200,
    unique=True)
    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',
                       args=[self.slug])
class Product(models.Model):
    category = models.ForeignKey(Category,
                                 related_name='products',
                                 on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d',
                              blank=True)
    description = models.TextField(blank=True)
    #stock = models.IntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)


    def get_absolute_url(self):
        return reverse('shop:product_detail',
                       args=[self.id, self.slug])

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)
    def __str__(self):
        return self.name

shop/views.py
from django.shortcuts import render, get_object_or_404, HttpResponse
from .models import Category, Product
from cart.forms import CartAddProductForm

def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'shop/product/list.html',
                  {'category': category, 'categories': categories,'products': products})

def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()
    return render(request,
                  'shop/product/detail.html',
                  {'product': product,
                   'cart_product_form':cart_product_form})

def shop(request):
    return render(request, 'shop/base.html')

shop/templates/shop/base.html
<!DOCTYPE html>
{% load static %}


<html>
    <head>
        <meta charset="utf-8" />
        <title>title>{% block title %}Mi tienda online{% endblock %}</title>
        <link href= "{% static 'css/base.css' %}" rel="stylesheet">
    </head>
    <header>
        <p align="right"><a href="{%url 'feedback:feedback_create' %}" class="button">Póngase en contacto con nosotros</a>
    </header>

    <header>

        {% if user.is_authenticated %}
            <p align="left">Hola {{ user.username }}!</p>
            <p><a href="{% url 'logout' %}" class="button">Log out</a></p>
        {% else %}
            <p>No ha iniciado la sesión.</p>
            <a href="{% url 'login' %}" class="button">Log In</a>
        {% endif %}
    </header>
    <header>
        <center>
            <p>Tienda de alimentación deportiva</p>
        </center>
        <center>
            <div id="header">
            <a href="/" class="logo">RED HOUND</a>
            <img src="{% static 'img/logo.png' %}" alt="Tienda de alimentación deportiva">
        </div>
        </center>

    </header>

    <body>
        <div id="subheader">
            <div class="cart">
            {% with total_items=cart|length %}
                {% if total_items > 0 %}
                    Su carrito de compras:
                    <a href="{% url 'cart:cart_detail' %}">
                    {{ total_items }} item{{ total_items|pluralize }},
                    €{{ cart.get_total_price }}
                    </a>
                {% else %}
                        Su carrito de compras está vacío.
                    {% endif %}
                {% endwith %}
        </div>
    </div>
        <div id="content">
            {% block content %}
            {%endblock %}
        </div>

    </body>

    <footer>
        <center>
             <p>Dirección: Turquía, Bursa, Nilüfer, Tel:+905348592913</p>
            <p>&copy; Todos los derechos reservados</p>
        </center>
    </footer>

</html>

shop/templates/shop/header.html
{% extends "shop/base.html" %}
{load static %}
<header>
    <center>
        <img src="{% static 'img/logo.png' %}" alt="Tienda de alimentación deportiva">
    </center>
</header>

shop/templates/shop/login.html
{% extends "shop/base.html" %}

{% block content %}
<h2>Log In</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
<button type="submit">Log In</button>
</form>
{% endblock content %}